[programs.devnet]
myepicproject = "7qarxMkggsgScNCePZ3uujCGWtMUebNtpwHKNFeT37ai"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/bidhanroy/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
